### ISSUE TITLE
[META] Feature Requests

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#122]
To avoid duplicate feature request and cluttering of the issue tracker, please comment any feature requests here and I'll keep a list. 

## Tag Key
✔️ = Completed pending new release
⭐ = Actively being worked on 
🗺️ = On the Road Map
🤚 = Requesting PR or Help
❌ = Unlikely to implemented, open to community support

## Authentication
 - [x] General User Authentication 
 - [ ] Secure API w/ Long Live Tokens

## Database Support
- [x] SQLite Support
- [ ] Postgres Support 🗺️ - Target 0.4.1 (Post Authentication Patch)

## General
- [x] Expanded Search Support 
   - [x] Search Description
- [x] Recipe Categories on Homepage 
- [x] Sort/Filter 
  - [x]  By Date
  - [x]  By Category
  - [x] By Tag
  - [x] Alphabetical 

## Recipe 
- [ ] Upload Image from URL ✔️
- [ ] Add All Schema.org items to Database Entry
- [ ] Add Waiting Time to Recipe
- [ ] Add Hardware/Tool requirements
- [x] Group Categories on Frontend
    - [x] Side-Bar Groups
- [ ] Bulk Category Management
    - [ ] View Uncategorized Recipes
    - [ ] Assign Categories in Bulk
- [ ] Calculate Nutrition Data - [Discussion](https://github.com/hay-kot/mealie/issues/109) ❌
- [ ] Printer Page 🤚
- [x] Markdown Support 
- [ ] Multiple Ingredients and Instruction Groups 🤚
- [ ] Adding Flavor Profile 🗺️
- [ ] Private/Public Recipes 🗺️
- [ ] Version Control ❌
- [ ] Add image support for recipe steps
### Editor
- [x] Scrollable Tag / Category Selector
- [x] Add Field for URL when manually adding a recipe 
- [x] Insert ingredient anywhere in ingredients list (Ingredients can now be moved in the editor. via drag-and-drop)

## Meal Planner
- [x] Generate mealplan Based on Rules 
- [x] Auto Set Start/End date in Meal Planner 
- [x] Auto Generate Shopping List 
- [ ] Multiple Recipes per Day 🗺️
- [ ] Leftovers / Ordering out Option - [Discussion](https://github.com/hay-kot/mealie/issues/97) 🗺️

## Migration from Other Apps
- [ ] Open Eats - [Discussion](https://github.com/hay-kot/mealie/issues/4) 🗺️

If anyone wants to help implement any of these features, I am available on the discord to help as much as I can.

**Comment by lylebrown** [comment]
It would be nice to be able to sort/reorder ingredients inside of individual recipes.

**Comment by dpieski** [comment]
I am not sure sort would really be useful since you would only be able to do a basic A-Z sort, but since each "ingredient" is a string that begins with a quantity, you would essentially just be weirdly sorting on quantity - Don't think the sorting that way would even make sense e.g., these ingredients would be in "alphabetical" order:

```
1 1/2 carrot
1 apple
1.25 banana
```

Reordering ingredients might be doable through a change to the UI during an edit though.

**Comment by hay-kot** [comment]
> It would be nice to be able to sort/reorder ingredients inside of individual recipes.

I'm currently playing around with a drag and drop reorder function in the editor.

**Comment by maguilara** [comment]
A tab or section for incomplete recipes or drafts, for someone experimenting with different ingredient proportions? Not sure how useful would really be, so really up to you :)

**Comment by rolamento** [comment]
Love the concept, Raspberry Pi Version is a must for million of us. Can you do it?

**Comment by thedeany** [comment]
The ability to edit serving size and auto-calculate ingredient list would be great. For example, if my base recipe is 2 servings and calls for 1 onion and I want to make 4 servings, I should be able to select "4 servings" and the ingredient list would then show "2 onion."

**Comment by sniperpirate** [comment]
Would it be possible to input some leftover ingredients which are on hand, and then mealie suggests all the recipes which are possible to use with those ingredients? Also, would it be possible to create a separate drinks / smoothie section?

Thank you for considering these suggestions and I hope you are all keeping safe & healthy!

**Comment by hay-kot** [comment]
> Love the concept, Raspberry Pi Version is a must for million of us. Can you do it?

There is an ARM image available. Are you having problems deploying?

**Comment by easybakechicken** [comment]
What about a bookmarklet or some type of extension that allows the addition of recipes without entering the UI.

**Comment by dpieski** [comment]
> The ability to edit serving size and auto-calculate ingredient list would be great.

@thedeany this feature would require that the ingredients are not simple strings. Check out #70, #109, #1 for more information on the thoughts regarding separating out the quantity from ingredients.

**Comment by sparklyballs** [comment]
Is it possible to strip any html tags and ampersand code from the ingredients and steps sections , or any other areas that shouldn't have them ? 
If i for instance import recipes from the bbc good food site i get a load of <p> and </pr> tags in the ingredients list and some imports from other sites i get ampersand codes especially &nbsp; etc...

**Comment by hay-kot** [comment]
> Is it possible to strip any html tags and ampersand code from the ingredients and steps sections , or any other areas that shouldn't have them ? 
> If i for instance import recipes from the bbc good food site i get a load of `<p>` and `</pr>` tags in the ingredients list and some imports from other sites i get ampersand codes especially `&nbsp;` etc...

This has been addressed. See https://github.com/hay-kot/mealie/issues/134

**Comment by sparklyballs** [comment]
> > Is it possible to strip any html tags and ampersand code from the ingredients and steps sections , or any other areas that shouldn't have them ?
> > If i for instance import recipes from the bbc good food site i get a load of `<p>` and `</pr>` tags in the ingredients list and some imports from other sites i get ampersand codes especially `&nbsp;` etc...
> 
> This has been addressed. See #134

My bad, although that issue doesn't mention html tags ? 

![Screenshot from 2021-02-02 15-30-52](https://user-images.githubusercontent.com/4343808/106622644-b5be8480-656b-11eb-8c05-817252521030.png)
(sorry for the big pic, just switched from kde to gnome and not sure how to screenshot just a section of the screen)

recipe imported from https://www.bbcgoodfood.com/recipes/cheeky-chicken-satay

**Comment by hay-kot** [comment]
@sparklyballs, I had misunderstood the scope. This is more of a bug than a feature. Best to create another issue so it can be tracked. I'll see what I can do.

**Comment by eric72777** [comment]
This may be related to closed issue #15 but it would be great if we could search by ingredients.

Thanks for making a great app! I'm running the arm64 docker image (Odroid N2) and it works great!

**Comment by FoxxMD** [comment]
Would love to have the contents of instructions and notes parsed as markdown to support formatting and lists.

**Comment by hay-kot** [comment]
> Would love to have the contents of instructions and notes parsed as markdown to support formatting and lists.

I'm actually looking into this for the next release, it should be fairly easy but I haven't dug too deep. Should resolve the line feed issue as well

**Comment by kllngtme** [comment]
With the amount of recipes I have myself and keep adding from other websites, is there a way to organize and view by categories rather? I'd like to build my own categories so I can, view my own recipes, or view different types of bread recipes or pasta recipes, rather than one page of everything.

Also, some of my recipes, it'd be nice to include more than one picture, is that something as well that could be added?

**Comment by hay-kot** [comment]
> With the amount of recipes I have myself and keep adding from other websites, is there a way to organize and view by categories rather? I'd like to build my own categories so I can, view my own recipes, or view different types of bread recipes or pasta recipes, rather than one page of everything.
> 
> Also, some of my recipes, it'd be nice to include more than one picture, is that something as well that could be added?

I've added category management into v0.2.0. Is that kind of what you were looking for? More improvements are coming to interfacing with categories and tags, but this is the first pass. As far as the multiple images, I'm not sure the use case. I like only have the one image to manage, but I'm open to ideas. 

<img width="1680" alt="Screen Shot 2021-02-08 at 3 38 05 PM" src="https://user-images.githubusercontent.com/64056131/107299454-e008ba00-6a23-11eb-8085-33bf0febd207.png">

**Comment by kllngtme** [comment]
Thanks, I've just upgraded after realizing that, but I'm getting a hard crash with the latest build on a pi4:

mealie         | Fatal Python error: init_interp_main: can't initialize time
mealie         | Python runtime state: core initialized
mealie         | PermissionError: [Errno 1] Operation not permitted
mealie         | 
mealie         | Current thread 0xb6fd8390 (most recent call first):
mealie         | <no Python frame>
mealie exited with code 1

**Comment by hay-kot** [comment]
> Thanks, I've just upgraded after realizing that, but I'm getting a hard crash with the latest build on a pi4:
> 
> mealie | Fatal Python error: init_interp_main: can't initialize time
> mealie | Python runtime state: core initialized
> mealie | PermissionError: [Errno 1] Operation not permitted
> mealie |
> mealie | Current thread 0xb6fd8390 (most recent call first):
> mealie |
> mealie exited with code 1

Looks like it's not an issue with Mealie. I was able to get this working with the fix here https://github.com/linuxserver/docker-papermerge/issues/4

Could you create an issue to help others who may have the same problem?

**Comment by sparklyballs** [comment]
> > With the amount of recipes I have myself and keep adding from other websites, is there a way to organize and view by categories rather? I'd like to build my own categories so I can, view my own recipes, or view different types of bread recipes or pasta recipes, rather than one page of everything.
> > Also, some of my recipes, it'd be nice to include more than one picture, is that something as well that could be added?
> 
> I've added category management into v0.2.0. Is that kind of what you were looking for? More improvements are coming to interfacing with categories and tags, but this is the first pass. As far as the multiple images, I'm not sure the use case. I like only have the one image to manage, but I'm open to ideas.
> 
> <img alt="Screen Shot 2021-02-08 at 3 38 05 PM" width="1680" src="https://user-images.githubusercontent.com/64056131/107299454-e008ba00-6a23-11eb-8085-33bf0febd207.png">

Not trying to second guess the OP's intent here, but it would be nice if the steps sections could have images, some recipes have them to show whatever you're trying to make should look like at various stages etc....
For example , here.... (this recipe won't import into mealie btw)

https://www.thespruceeats.com/slow-roasted-pork-belly-crispy-skin-3059509

**Comment by hay-kot** [comment]
> Not trying to second guess the OP's intent here, but it would be nice if the steps sections could have images, some recipes have them to show whatever you're trying to make should look like at various stages etc....
> For example , here.... (this recipe won't import into mealie btw)
> 
> https://www.thespruceeats.com/slow-roasted-pork-belly-crispy-skin-3059509

This makes total sense to me. I've added it to the list. It'll take some reworking of the database and the UI so it may be a little ways out, but it should be *fairly simple*.

**Comment by MI3Guy** [comment]
Would it be possible to add tags for each version on docker hub? I'm currently using the sha256 to pin the version so I control when the updates occur.

**Comment by hay-kot** [comment]
> Would it be possible to add tags for each version on docker hub? I'm currently using the sha256 to pin the version so I control when the updates occur.

I'd love to support this. I'm unsure how to implement it into the current Github workflow. I wasn't able to find a quick answer on using a variable/version number in python to set the tag in the Github workflow. I'd like to have a single source of truth for version somewhere in the code that then gets mapped to docker and the frontend. I'm open to ideas on how to accomplish this.

**Comment by sparklyballs** [comment]
> > Would it be possible to add tags for each version on docker hub? I'm currently using the sha256 to pin the version so I control when the updates occur.
> 
> I'd love to support this. I'm unsure how to implement it into the current Github workflow. I wasn't able to find a quick answer on using a variable/version number in python to set the tag in the Github workflow. I'd like to have a single source of truth for version somewhere in the code that then gets mapped to docker and the frontend. I'm open to ideas on how to accomplish this.

https://docs.docker.com/docker-hub/builds/#advanced-automated-build-options

**Comment by gear4s** [comment]
you should allow use to specify a root URI for requests; I'm setting up https://cloud.aaronleem.co.za/mealie/ and cannot get URIs to work

**Comment by hay-kot** [comment]
> you should allow use to specify a root URI for requests; I'm setting up https://cloud.aaronleem.co.za/mealie/ and cannot get URIs to work

Duplicate #136

**Comment by wengtad** [comment]
Request to have a feature to clone/duplicate on recipe, so that we could clone the same recipe out to a new one (by adding in Copy/Clone wording on the name). The use case will be user able to clone from original recipe (must existed on Mealie) and do some adjustment/modification on new to become version 2, 2.1 or 3 (by changing the name or anyway they like). It is for the person who want to do some experiment on the recipe to create his/her own favorite recipes. 

Thinking about this, adding a new feature request to allow them to mark the recipe as "Good" or "Bad" recipe? (I think this can be ignore, since already have rating feature)

Open to all for discussion, whether these 2 feature requests would include on Mealie or not.

**Comment by MrPeanut12** [comment]
I would love to see "view options" -- in particular, a list view (see attached).
![2021-02-20](https://user-images.githubusercontent.com/43787798/108600006-70b79200-7362-11eb-98ad-850bd97c1234.jpg)

**Comment by hay-kot** [comment]
> I would love to see "view options" for the recipe listing -- in particular, a list view ([see screenshot](https://user-images.githubusercontent.com/43787798/108600006-70b79200-7362-11eb-98ad-850bd97c1234.jpg) for an example).

Love this idea. Any thoughts on how this would work on mobile/desktop? Should it be a global thing you set in settings, or perhaps a a toggle on section headers? Maybe a default view settings for mobile and desktop...

**Comment by MrPeanut12** [comment]
> 
> 
> > I would love to see "view options" for the recipe listing -- in particular, a list view ([see screenshot](https://user-images.githubusercontent.com/43787798/108600006-70b79200-7362-11eb-98ad-850bd97c1234.jpg) for an example).
> 
> Love this idea. Any thoughts on how this would work on mobile/desktop? Should it be a global thing you set in settings, or perhaps a a toggle on section headers? Maybe a default view settings for mobile and desktop...

Hmm, I'm not exactly sure. I think I would like to go into settings and set my desktop view as "grid" and my mobile view as "list" (or perhaps both "list"). I probably wouldn't expect to see a toggle on section headers since I likely wouldn't switch.

**Comment by hay-kot** [comment]
> Would it be possible to add tags for each version on docker hub? I'm currently using the sha256 to pin the version so I control when the updates occur.

I was able to get this working. Release tagged docker images are now built as part of the CI/CD pipeline 🎉

**Comment by kophi** [comment]
My Mealie installation (Docker, 0.3.0) includes JavaScript from https://cdn.jsdelivr.net/ which makes it not fully self hosted. Please include the required JS code in the Docker container. Thank you :-)

**Comment by kllngtme** [comment]
This recipe isn't able to be parsed but besides that. This recipe has multiple parts for the ingredients list (Crust, Cream Cheese Layer, Pudding Layer, Topping). Is there a way to incorporate this idea for the ingredients for multi-part recipes?

**Comment by hay-kot** [comment]
> This recipe isn't able to be parsed but besides that. This recipe has multiple parts for the ingredients list (Crust, Cream Cheese Layer, Pudding Layer, Topping). Is there a way to incorporate this idea for the ingredients for multi-part recipes?

If you are having trouble parsing a website, fill out a bug report. Multiple ingredients and instructions groups are planned but it's a big rework to be able to support multiple data structures in the database  so it is going to take some time.

**Comment by simeonradivoev** [comment]
* Recipe Translations - would be nice to be able to have different translations for the same recipe.
* Video Links - Video links for recipes would also be nice

**Comment by jrhorrisberger** [comment]
Meal Planner - Drag and drop. To allow reordering the meal plan options. Either by swapping places or shifting everything down. Not sure which would be best. Maybe Swapping places? e.g. drag Friday to Monday to swap places.

**Comment by waschinski** [comment]
Customize recipe - Allow customizing (basically copying) an existing recipe to adjust certain parts. An use case for that could be to make a non-vegan/vegetarian recipe vegan/vegetarian. A link to the original recipe could be provided on the new recipe.

**Comment by tehniemer** [comment]
Include the link to the original recipe location.

**Comment by MrPeanut12** [comment]
> 
> 
> Include the link to the original recipe location.

I think this is already a feature. At the bottom right, I have an "Original URL" button.

![2021-02-28_15 47 30](https://user-images.githubusercontent.com/43787798/109433050-59207f00-79dc-11eb-8a87-cfc419a2bf16.png)

**Comment by tehniemer** [comment]
I don't have that in mine, running the docker version.

**Comment by hay-kot** [comment]
> > Include the link to the original recipe location.
> 
> I think this is already a feature. At the bottom right, I have an "Original URL" button.
> 
> ![2021-02-28_15 47 30](https://user-images.githubusercontent.com/43787798/109433050-59207f00-79dc-11eb-8a87-cfc419a2bf16.png)

Automatic source import was broken during a refactor. It's been fixed, but I'm still working on the next release. Since it's a small bug I wasn't planning on rolling a patch out in the meantime.

**Comment by tehniemer** [comment]
Will recipes have to be re-uploaded or is that info saved somewhere already?

**Comment by hay-kot** [comment]
> Will recipes have to be re-uploaded or is that info saved somewhere already?

It is not saved anywhere. You can manually add the URL with the editor at any time though. There's a field at the bottom of the page

**Comment by tehniemer** [comment]
Got it, thanks.

**Comment by Soldierbane** [comment]
I'd love to see a feature where you could manually input how many servings are in a recipe and how many calories are in the recipe so that it can calculate the calories/serving and show it on the meal planner.

**Comment by GHSTUDIO1** [comment]
I've worked with Mealie for just one day....but I think it's important to get a new user's perspective on suggested improvements.....  I did not read any "how to use" documentation......and I'm not sure any exists other than the one video....but most users today don't read documentation, so a UI really needs to be "self explanatory".....ease of use without having to read how to use stuff.

1) search doesn't do what's expected. Currently it only searches recipe titles but it should be able to search on any word in a recipe (eg. ingredient).  Maybe a drop down to give you choices: titles only; ingredients only; tags only; etc.  eg: I want to see all recipes that use Tofu

2) what are tags used for?  the only use I can find is that they are shown when you open a recipe.  tied to 1 above, I though at least I could search for a tag.

3) There is no way to find if you have a recipe that has not been categorized yet.  there should be an easy way to show only uncategorized recipes.....so user can categorize the one's they missed.

4) I would like to categorize by country (Chinese, Icelandic,...) and by type of meal (soup, appetizer,...).  I find that they are all listed together in the left column alphabetically so they are mixed.  would be nice to be able to separate categories into groups.

5) I can create backups and upload them somewhere.....but how do I restore them?

6) Is the URL of the original recipe saved somewhere....I see a field for "original URL", but it's blank.  

7) I think a user needs to be able to refer back to the original URL easily just to review other comments that usually accompany a recipe. I though I saw something in the video...but I don't think it's in the installed version.

8) as others have said, there needs to be a way to tell what version a user is running.......about:   or in settings....but somewhere.

9) when entering a category there is a drop down box, but if you have more categories defined, there's no way to scroll so you have to remember every category or search based on the first letter, etc.  It would be helpful if that drop down box was scrollable.

note: I probably should have posted in separate notes because it's easier to track suggestions that way....guilty of laziness :)

**Comment by hay-kot** [comment]
>  I did not read any "how to use" documentation......and I'm not sure any exists other than the one video

In the README for the GitHub repository there is a link to what I think is fairly extensive documentation. Not reviewing documentation for the FOSS project before providing feedback is unfair to contributors and creators. I've spent a lot of time putting that documentation together to help others use something I made initially made for myself. 

> but most users today don't read documentation, so a UI really needs to be "self explanatory".....ease of use without having to read how to use stuff.

I would like to point out that this is free software that I have spent significant amount of my time creating, making deployable, and providing documentation for. I do not make any money off of this other than the small donations that some community members have made. Given that, I think it's unfair to assume or expect that a user would not need to review any documentation prior to use, especially consider this is still a BETA release. 

For the feature requests in your post, I've added them to this issue to track. 

> I can create backups and upload them somewhere.....but how do I restore them?

[That is Covered in the Documentation](https://hay-kot.github.io/mealie/getting-started/backups-and-exports/)

> Is the URL of the original recipe saved somewhere....I see a field for "original URL", but it's blank.

[See This Issue](https://github.com/hay-kot/mealie/issues/179)

> as others have said, there needs to be a way to tell what version a user is running.......about: or in settings....but somewhere.

This is shown at the foot of the settings page, along with the latest version and a link to documentation. Versions can also be pinned from the image tag. 

---

In the future please separate issues/bugs and feature requests so we don't clutter up this thread. I appreciate your insight and hope you'll consider contributing to the project and helping develop some of the features you're requesting. Thanks!

**Comment by GHSTUDIO1** [comment]
I think it’s a wonderful program…..don’t take my comments wrong.  I’ve been involved with future products and testing user interfaces for years professionally, so I looked at your program through those eyes.  I know it’s a work in progress….amazingly complete…and potentially lucrative.

 

I clearly missed a few things....due to what have become informal, undocumented internet standards…such as the version number and an “about” section somewhere.  As far as users reading instructions, my assumption is that you are aiming at a wider audience than just techies…..and the wider audience is different than you and I….they don’t read instructions, they get confused easily….sometimes the hardest part of a project is getting the interface right.  I did not read through every open issue…so the missing original URL was indeed a repeat.  I think you had a link to the original URL when someone opens a recipe and that’s a big plus….most recipes these days have some prose around them that’s occasionally helpful.

 

I looked through the documentation and didn’t find anything about tags other than you could add them.  I think they’re important if you can search/sort on them….I would have made soup or entree a tag rather than a category.  It would be nice to sort Hungarian recipes by tag or list by tag, etc.  Likely you have something in mind for future releases.

 

Anxious to get all my recipes easily gathered in one place.  There were a few URL’s that didn’t work well…but no way to handle all sites.  In one case, there was a print option so I got the URL for the print formatted page, but that didn’t help. I’m more of an ethnic recipe cook and find some off the beaten track sites with recipes.

 

I’ve added mealie to my home server…debian and docker managed by portainer. I’ll be experimenting with Proxmox, but don’t expect any unusual interaction.  If you are ok with a little advertising, I’ll do some posts on a few Home Assistant forums…I think there’s a lot of synergy between the two softwares.

 

Doug

**Comment by Tooa** [comment]
I would like to create non-interactive backups via `docker exec [...]`. The command should create a zip file with the exported data in a folder. I can then use a docker host mounts for that folder to access the backup file on my host. The latter allows me to save the archive somewhere else.

**Comment by waschinski** [comment]
> ## Feature Request 1
> I would like to create non-interactive backups e.g. via `docker exec [...]`. The command should create a zip file with the exported data in a folder. I can then use a docker host mount for that folder to access the backup file on my host. The latter allows me to save the archive somewhere else.
Have you taken a look inside the data volume? There's a backup folder already and I can see an auto created zip file inside there for my installation.

**Comment by Tooa** [comment]
> Have you taken a look inside the data volume? There's a backup folder already and I can see an auto created zip file inside there for my installation.

You are right! The backup page of the application states `Automated backups are done each day at 3:00 AM. `.  I just had a look into the documentation [here](https://hay-kot.github.io/mealie/getting-started/backups-and-exports/) where the automatic backup isn't mentioned. Then I suggest to add this information to the documentation.

**Comment by waschinski** [comment]
I only have one automatic backup file in the backup folder so I am pretty sure it's getting replaced each night.

If you would like to keep each backup separately or want it to be more flexible, you could also just build a simple container which also mounts the mealie data folder and grab it from inside there. Similar to what Bruceforce/bitwarden_rs-backup does, I think.

**Comment by hay-kot** [comment]
> Does the automatic backup create a new unique one every day? 

Only 1 Automatic backup can exists. This is done by pattern matching the backup name. So simply changing the name will allow you to retain additional backups

> What about a retention policy to control the number of backups from growing? Is changing the backup schedule possible?

This was something I looked into. It's a lot of configuration to handle and I'm tasked with some many other features that I think are more core to the application that are taking priority. I'm open to anyone willing to support additional options for backups though. 

> I like the `docker exec` approach instead, because a user can schedule the time and the number of backups for example with Cron. Further via a command line argument one could override the default zip file name.

I'm unlikely to implement anything via the `docker exec` approach. All of this can already be accomplished via the API. Check out the docs at https://your-mealie-instance.com/docs. Under Backups the `/api/backups/export/database` end point can be used to generate a backup. via POST with a payload like the one below. You can even use wget to retrieve the file remotely.

```
{
  "tag": "July 23rd 2021",
  "options": {
    "recipes": true,
    "settings": true,
    "themes": true
  },
  "template": [
    "recipes.md"
  ]
}
```

 The interactive documentation will also generate a `curl` command that can help you in creating a CRON job. Anything being done from the frontend can be done via the API. Better documentation for the API is coming with additional documentation for the site in general.

**Comment by 1v0dev** [comment]
Great app. Feature request: add integration with external API to automatically calculate recipe calories. There are a few free ones that should be easy to integrate. For example, https://developer.edamam.com/edamam-nutrition-api-demo. You can put a setting for the API key so each installation can use a separate API account.

**Comment by carlyman** [comment]
Feature Request: Custom Pages based on Tags rather than just Categories.  (as other requests have called out, I'd like to leverage tags more via search, click-to-filter, etc).

P.S. Can't overstate that v0.4 is awesome, really is a great MVP for my family's daily usage.

**Comment by hay-kot** [comment]
> Feature Request: Custom Pages based on Tags rather than just Categories. (as other requests have called out, I'd like to leverage tags more via search, click-to-filter, etc).
> 

Thanks for the kind words!

I don't have a good idea on what to do with tags overall. They exists...but that's pretty much it. If you or anyone else has ideas, [checkout the tags discussion](https://github.com/hay-kot/mealie/discussions/242). I need help structuring how this is going to work. In the beginning it seemed obvious what they were, but the more I talk to my wife the less I feel like I understand, lol.

**Comment by antoine2tt** [comment]
Thank you for that amazing 0.4 ! 

Feature Request : Permissions for "Visitors", being able to choose if visitors can "View (All/some) Receipe" "Add Receipe" "Edit/Delete Receipe"

**Comment by dietrichmd** [comment]
It would be nice to display the original URL somewhere on the recipe page.  It exists in the edit function, but not on a live recipe.

**Comment by carlyman** [comment]
> It would be nice to display the original URL somewhere on the recipe page. It exists in the edit function, but not on a live recipe.

There's a button on the bottom right of the live recipe ("Original URL") -- I like that its available, but also subtle.

**Comment by sephrat** [comment]
Feature idea: a "Cook now!" button on a recipe page to go into "cook mode" and have a nice step-by-step interface.
Maybe this could overall be improvements to the current page, but I feel like you need to read the recipe in a different view when you plan it from when you actually cook it.

- Ingredients list is always visible (today I need to scroll up to remember how many grams of flour I need in step 10)
- Better navigation between steps ( https://vuetifyjs.com/en/components/steppers/ could look great)
- A fancy timer you can set, manually or based on the cook time (https://vuetifyjs.com/en/components/progress-circular/#rotate ?). 
- After completing the last step, some congratulation page (did I just make up a Kids Acceptance Factor?) where we say "Bon appétit !" and ask the user to rate the recipe. 
- Remember when you last cooked this meal, and display it in some places: on the recipe page and in the meal planner for example?

I know, it's a big one. It's been growing on me lately, I thought I would lay it on the table somewhere. Maybe I could POC this when I get the time.

**Comment by dietrichmd** [comment]
Better print layout?  Currently, recipes get lopped off or split up due to the way the data is laid out.  What could easily be displayed on one page often comes out on 2+ pages.  And printing the image would be nice too.  I'm sure all this is in the pipeline somewhere, but I wanted to bring it up jic :)

**Comment by jayenicks** [comment]
Feature Request: Agility to edit/delete tags and categories. I misspelled a tag and can't seem to find a way to remove it from the list of recommendations.

**Comment by ovizii** [comment]
Unit conversion would be great if that is possible. i.e. if I scrape a recipe from a website I sometimes end up with measurement units which are different than what I am used to here in Europe. 

If not possible, I have to manually edit and convert each added recipe's measurements.

**Comment by ovizii** [comment]
I would very much like to see a more detailed explanation on how to use custom pages. I read this but I don't fully understand how and where to sue custom pages. https://hay-kot.github.io/mealie/getting-started/organizing-recipes/

**Comment by ovizii** [comment]
Why exactly are the instruction steps clickable? I'm just wondering what the purpose is as nothing happens besides changing the formatting of that particular step. 
![image](https://user-images.githubusercontent.com/837902/114996941-a62eb680-9e9f-11eb-85ec-7de74709b93f.png)

**Comment by sephrat** [comment]
> Why exactly are the instruction steps clickable? I'm just wondering what the purpose is as nothing happens besides changing the formatting of that particular step. In this screenshot you can see step 2 looks different after I click on it. Another click changes the display back to the way it was before.
> ![image](https://user-images.githubusercontent.com/837902/114996941-a62eb680-9e9f-11eb-85ec-7de74709b93f.png)
> 

Please stay on topic so that feature requests don't get lost in the flow. We have a Discord and Github discussions page for this. 
Thanks

**Comment by ovizii** [comment]
> Please stay on topic so that feature requests don't get lost in the flow. We have a Discord and Github discussions page for this.
> Thanks
I apologize and will move my questions there. I wasn't aware of those options, sorry again.

**Comment by veonru** [comment]
First of all, thank you for this amazing project. Just what I was looking for.

Now, on to my Feature Request:
I'd be great to have the ability to set the dark theme as default, for example via environment variable. Or maybe tie the setting to the user account instead of the browser. Hope you'll consider it and thanks!

**Comment by dietrichmd** [comment]
It would be great if we had multi-item ingredients and instructions.  For instance, a recipe has a fried rice component and a protein component.  Currently, no easy way to separate the two.

**Comment by hay-kot** [comment]
I'm going to close this thread and move it to a [discussion](https://github.com/hay-kot/mealie/discussions/316), It's getting difficult to track and respond to new requests. I've gone through and added all the requests to the new thread.

If I missed your request you can go yell at me over there. Cheers!
