### ISSUE TITLE
[META] Feature Request

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#317]
# New Feature Request Process

**Feature Requests Should be Submitted as Discussions**

Give the sheer size (300+) of the original discussion page and some low effort feature requests I'm locking the thread and will now adopt a more structured Feature Request process. For the sake of my sanity please try to follow the below steps to the best of your ability. 

## Step 1: Review open request

Prior to posting a feature request, please review all open/closed feature requests. If your feature has already been posted you can add additional comments in the discussion and/or add an 👍. The more activity on a request gives me a better idea of what to prioritize. DO NOT open duplicate features requests. 

## Step 2: Open Feature Request

Copy and paste the template below to use for your request. If you don't use this format your request will be removed. 

* Be sure to tag your request with the appropriate discussion category

```markdown

**Before submitting this feature request I have**
_COMPLETE AND FILL THESE OUT_
- [ ] Reviewed the documentation and verified that my feature request isn't already a feature.
- [ ] Reviewed the existing feature requests and my feature has not been requested.
- [ ] Checked the [tasks taged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

**Please Describe The Problem To Be Solved**
_REPLACE-THIS-TEXT: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope._

**(Optional): Suggest A Solution**
_Replace This Text: A concise description of your preferred solution. Things to address include:_
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Additional Information**
_FILL THESE OUT_
- [ ] If the feature is accepted I'm willing to submit a PR to provide this feature

```
